const SUPABASE_URL='https://ghspaqawzfqtsxibgqxy.supabase.co';
const SUPABASE_KEY='sb_publishable_zzfaJaBr-schcxD7EMh3wA_69Vx1Xsg';
const WA_NUMBER='5518981485892';
const demoPros=[
{id:'p1',name:'Rafael Martins',role:'Garçom • Barman',rating:4.9,reviews:12,rate:150,match:96,tags:['Noite','Fim de semana','Transporte'],img:'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=85'},
{id:'p2',name:'Juliana Costa',role:'Auxiliar de cozinha',rating:4.8,reviews:9,rate:130,match:91,tags:['Tarde','Noite','Experiência'],img:'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=85'},
{id:'p3',name:'Carlos Silva',role:'Churrasqueiro • Serviços gerais',rating:4.7,reviews:15,rate:180,match:88,tags:['Fim de semana','Transporte'],img:'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=85'},
{id:'p4',name:'Ana Paula',role:'Recepção • Eventos',rating:4.9,reviews:20,rate:140,match:94,tags:['Manhã','Tarde','Eventos'],img:'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=85'}];
const demoJobs=[
{id:'o1',title:'2 garçons para evento',company:'Espaço Aurora Eventos',cat:'Garçom',date:'Sáb, 12/09',time:'18h às 01h',rate:160,v:2,match:96,img:'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1000&q=85'},
{id:'o2',title:'Auxiliar de cozinha',company:'Sabor da Terra',cat:'Cozinha',date:'Sex, 11/09',time:'16h às 00h',rate:140,v:1,match:90,img:'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1000&q=85'},
{id:'o3',title:'Equipe de limpeza',company:'Hotel Prime',cat:'Limpeza',date:'Dom, 13/09',time:'08h às 17h',rate:130,v:4,match:87,img:'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1000&q=85'}];
const demoCompanies=[
{id:'c1',name:'Espaço Aurora Eventos',kind:'Eventos',rating:4.8,jobs:14,img:'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=600&q=80'},
{id:'c2',name:'Sabor da Terra',kind:'Restaurante',rating:4.7,jobs:19,img:'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=600&q=80'},
{id:'c3',name:'Hotel Prime',kind:'Hotelaria',rating:4.9,jobs:9,img:'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80'},
{id:'c4',name:'Ponto da Brasa',kind:'Gastronomia',rating:4.8,jobs:17,img:'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=600&q=80'}];
const categories=[['🍽️','Garçom'],['🍸','Barman'],['🧹','Diarista'],['🎨','Pintor'],['🧽','Faxineira'],['⚡','Eletricista'],['🌿','Jardineiro'],['•••','Outros']];
let publicPros=[],publicJobs=[],publicCompanies=[],metrics={signups:0,hiring_requests:0,confirmed_whatsapp:0,approved_professionals:0,published_opportunities:0};
let state=JSON.parse(localStorage.getItem('it_free_stack')||'{"fav":[],"apps":["o1"],"selected":"o1","service":{"pro":false,"company":false,"done":false}}');
const save=()=>localStorage.setItem('it_free_stack',JSON.stringify(state));
const $=id=>document.getElementById(id);
function toast(msg){const el=document.createElement('div');el.className='toast';el.textContent=msg;$('toastRoot').appendChild(el);setTimeout(()=>el.remove(),2400)}
function go(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('is-active'));$('screen-'+id)?.classList.add('is-active');document.querySelectorAll('[data-nav]').forEach(x=>x.classList.toggle('is-active',x.dataset.nav===id));scrollTo({top:0,behavior:'smooth'});if(id==='painel')renderPanel();if(id==='operacao')renderOps()}
function modal(html){$('modalRoot').innerHTML=`<div class="modal-bg"><div class="modal">${html}</div></div>`;$('modalRoot').querySelector('.modal-bg').addEventListener('click',e=>{if(e.target.classList.contains('modal-bg'))closeModal()})}
function closeModal(){$('modalRoot').innerHTML=''}
function proCard(p,isReal=false){return `<article class="card"><div class="card__media"><img src="${p.img||'https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=800&q=80'}" alt="Foto ilustrativa"><span class="badge ${isReal?'badge--green':'badge--blue'}" style="position:absolute;left:12px;top:12px">${isReal?'PERFIL APROVADO':'DEMO · FOTO ILUSTRATIVA'}</span></div><div class="card__body"><h3>${p.name}</h3><div class="muted small">${p.role}</div><div class="rating">⭐ ${p.rating||0} <span class="muted">(${p.reviews||0})</span></div><div class="tags">${(p.tags||[]).map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="money">${p.rate?`R$ ${p.rate}/dia`:'Valor a combinar'}</div><div class="matchline"><span class="small muted">${p.match||85}% match</span><div class="matchbar"><span style="width:${p.match||85}%"></span></div></div><div class="card-actions"><button class="btn btn--outline" onclick="openPro('${p.id}',${isReal})">Ver perfil</button></div></div></article>`}
function jobCard(o,isReal=false){const fav=state.fav.includes(o.id);return `<article class="card"><div class="card__media"><img src="${o.img||'https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1000&q=80'}" alt="Imagem da oportunidade"><span class="badge ${isReal?'badge--green':'badge--orange'}" style="position:absolute;left:12px;top:12px">${isReal?'VAGA PUBLICADA':'OPORTUNIDADE DEMO'}</span></div><div class="card__body"><div class="muted small">${o.company}</div><h3>${o.title}</h3><div class="meta"><span>📅 ${o.date||'A combinar'}</span><span>⏰ ${o.time||'A combinar'}</span><span>💚 ${o.match||90}% match</span></div><div class="money">${o.rate?`R$ ${o.rate}/dia`:'Valor a combinar'}</div><div class="card-actions"><button class="btn btn--green" onclick="openJob('${o.id}',${isReal})">Ver vaga</button><button class="btn btn--outline fav" onclick="toggleFav('${o.id}')">${fav?'♥':'♡'}</button></div></div></article>`}
function companyCard(c,isReal=false){return `<article class="card company-card"><div class="company-head"><img class="company-photo" src="${c.img||'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=500&q=80'}"><div><span class="badge ${isReal?'badge--green':'badge--blue'}">${isReal?'CADASTRO APROVADO':'EMPRESA DEMO'}</span><h3>${c.name}</h3><div class="muted small">${c.kind}</div></div></div><div class="meta"><span>⭐ ${c.rating||0}</span><span>${c.jobs||0} contratações</span></div><button class="btn btn--outline" style="width:100%" onclick="openCompany('${c.id}',${isReal})">Ver empresa</button></article>`}
function renderCategories(){$('categoryGrid').innerHTML=categories.map(([i,n])=>`<button class="category" onclick="filterCategory('${n}')"><span class="category__icon">${i}</span><b>${n}</b></button>`).join('')}
function currentPros(){return publicPros.length?publicPros:demoPros}function currentJobs(){return publicJobs.length?publicJobs:demoJobs}function currentCompanies(){return publicCompanies.length?publicCompanies:demoCompanies}
function renderHome(){$('homePros').innerHTML=currentPros().slice(0,4).map(p=>proCard(p,publicPros.length>0)).join('');$('homeJobs').innerHTML=currentJobs().slice(0,3).map(o=>jobCard(o,publicJobs.length>0)).join('');$('homeCompanies').innerHTML=currentCompanies().slice(0,4).map(c=>companyCard(c,publicCompanies.length>0)).join('')}
function renderPros(){let q=($('proQuery')?.value||'').toLowerCase(),cat=$('proCategory')?.value||'',ord=$('proOrder')?.value||'match';let arr=currentPros().filter(p=>(!q||`${p.name} ${p.role} ${(p.tags||[]).join(' ')}`.toLowerCase().includes(q))&&(!cat||p.role.includes(cat)));arr.sort((a,b)=>ord==='rating'?(b.rating||0)-(a.rating||0):ord==='rate'?(a.rate||9999)-(b.rate||9999):(b.match||0)-(a.match||0));$('proGrid').innerHTML=arr.map(p=>proCard(p,publicPros.length>0)).join('')}
function renderJobs(){let q=($('jobQuery')?.value||'').toLowerCase(),cat=$('jobCategory')?.value||'',ord=$('jobOrder')?.value||'match';let arr=currentJobs().filter(o=>(!q||`${o.title} ${o.company} ${o.cat}`.toLowerCase().includes(q))&&(!cat||o.cat===cat));arr.sort((a,b)=>ord==='rate'?(b.rate||0)-(a.rate||0):(b.match||0)-(a.match||0));$('jobGrid').innerHTML=arr.map(o=>jobCard(o,publicJobs.length>0)).join('')}
function renderCompanies(){$('companyGrid').innerHTML=currentCompanies().map(c=>companyCard(c,publicCompanies.length>0)).join('')}
function toggleFav(id){const i=state.fav.indexOf(id);i>=0?state.fav.splice(i,1):state.fav.push(id);save();renderJobs();renderHome();toast(i>=0?'Removido dos favoritos':'Salvo nos favoritos')}
function filterCategory(cat){go('vagas');$('jobCategory').value=['Garçom','Barman'].includes(cat)?cat:'';renderJobs()}
function openPro(id,isReal){const list=isReal?publicPros:demoPros,p=list.find(x=>x.id===id);if(!p)return;modal(`<div class="notice">${isReal?'✅ Perfil público aprovado.':'👤 Perfil fictício com foto ilustrativa realista.'}</div><h2>${p.name}</h2><p class="muted">${p.role} · ${p.city||'Teodoro Sampaio - SP'}</p><div class="kpi-grid"><div class="kpi"><strong>${p.rating||0}</strong><span>Nota</span></div><div class="kpi"><strong>${p.reviews||0}</strong><span>Avaliações</span></div><div class="kpi"><strong>${p.rate?`R$ ${p.rate}`:'—'}</strong><span>Diária</span></div><div class="kpi"><strong>${p.match||85}%</strong><span>Match</span></div></div><div class="modal-actions"><button class="btn btn--green" onclick="toast('Contato liberado somente após o fluxo correto')">Tenho interesse</button><button class="btn btn--outline" onclick="closeModal()">Fechar</button></div>`)}
function openCompany(id,isReal){const list=isReal?publicCompanies:demoCompanies,c=list.find(x=>x.id===id);if(!c)return;modal(`<div class="notice">${isReal?'✅ Empresa pública aprovada.':'🏢 Empresa fictícia da demonstração.'}</div><h2>${c.name}</h2><p class="muted">${c.kind} · ${c.city||'Teodoro Sampaio - SP'}</p><div class="kpi-grid"><div class="kpi"><strong>${c.rating||0}</strong><span>Reputação</span></div><div class="kpi"><strong>${c.jobs||0}</strong><span>Contratações</span></div><div class="kpi"><strong>Local</strong><span>Atuação</span></div><div class="kpi"><strong>✅</strong><span>Cadastro</span></div></div><button class="btn btn--outline" onclick="closeModal()">Fechar</button>`)}
function openJob(id,isReal){const list=isReal?publicJobs:demoJobs,o=list.find(x=>x.id===id);if(!o)return;const applied=state.apps.includes(id);modal(`<div class="notice">${isReal?'💼 Oportunidade publicada. Candidatura real entra quando ativarmos login.':'💼 Oportunidade fictícia da demonstração.'}</div><h2>${o.title}</h2><p class="muted">${o.company} · ${o.cat}</p><div class="meta"><span>📅 ${o.date||'A combinar'}</span><span>⏰ ${o.time||'A combinar'}</span><span>👥 ${o.v||1}</span></div><div class="money">${o.rate?`R$ ${o.rate}/dia`:'Valor a combinar'}</div><div class="modal-actions"><button class="btn btn--green" ${applied?'disabled':''} onclick="applyDemo('${id}')">${applied?'✅ Interesse enviado':'Tenho interesse'}</button><button class="btn btn--outline" onclick="closeModal()">Fechar</button></div>`)}
function applyDemo(id){if(!state.apps.includes(id))state.apps.push(id);save();closeModal();renderPanel();toast('Interesse registrado na demonstração')}
function selectDemo(){state.selected='o1';save();renderPanel();toast('Candidato selecionado')}
function confirmDemo(side){state.service[side]=true;save();renderPanel();toast('Confirmação registrada')}
function completeDemo(){state.service.done=true;save();renderPanel();reviewModal()}
function renderPanel(){const s=state.service;$('panelKpis').innerHTML=[['4,9','Nota demo'],[state.apps.length,'Candidaturas'],[state.fav.length,'Favoritos'],[(s.pro&&s.company)?'2/2':'0-2/2','Confirmações']].map(k=>`<article class="kpi"><strong>${k[0]}</strong><span>${k[1]}</span></article>`).join('');$('serviceFlow').innerHTML=`<div class="list-row"><div class="grow"><b>Interesse na vaga</b><div class="small muted">Rafael demonstrou interesse.</div></div><span class="status status--ok">Concluído</span></div><div class="list-row"><div class="grow"><b>Seleção do candidato</b></div>${state.selected?'<span class="status status--ok">Selecionado</span>':'<button class="btn btn--navy" onclick="selectDemo()">Selecionar</button>'}</div><div class="list-row"><div class="grow"><b>Profissional confirma</b></div>${s.pro?'<span class="status status--ok">Confirmado</span>':'<button class="btn btn--outline" onclick="confirmDemo(\'pro\')">Confirmar</button>'}</div><div class="list-row"><div class="grow"><b>Empresa confirma</b></div>${s.company?'<span class="status status--ok">Confirmado</span>':'<button class="btn btn--outline" onclick="confirmDemo(\'company\')">Confirmar</button>'}</div><div class="list-row"><div class="grow"><b>Concluir e avaliar</b></div>${s.done?'<span class="status status--ok">Finalizado</span>':(s.pro&&s.company?'<button class="btn btn--green" onclick="completeDemo()">Concluir</button>':'<span class="status status--wait">Aguardando</span>')}</div>`;$('candidateList').innerHTML=demoPros.map((p,i)=>`<div class="list-row"><img class="company-photo" src="${p.img}"><div class="grow"><b>${p.name}</b><div class="small muted">${p.role} · ⭐ ${p.rating}</div></div><span class="status ${i===0?'status--ok':'status--wait'}">${i===0?'96% match':'Disponível'}</span></div>`).join('')}
function renderOps(){$('opsKpis').innerHTML=[[metrics.signups,'Pré-cadastros reais'],[metrics.hiring_requests,'Pedidos reais'],[metrics.confirmed_whatsapp,'WhatsApps confirmados'],[metrics.approved_professionals,'Perfis publicados']].map(k=>`<article class="kpi"><strong>${k[0]}</strong><span>${k[1]}</span></article>`).join('');$('opsQueue').innerHTML=`<div class="list-row"><div class="grow"><b>Cadastros reais protegidos</b><div class="small muted">Os dados pessoais estão no Supabase e não são expostos neste painel público.</div></div><span class="status status--ok">RLS ativo</span></div><div class="list-row"><div class="grow"><b>Confirmação manual de WhatsApp</b><div class="small muted">Fluxo gratuito do piloto.</div></div><span class="status status--wait">Operação</span></div>`;$('incidentList').innerHTML=`<div class="list-row"><div class="grow"><b>No-show reportado</b><div class="small muted">Exemplo: aguarda revisão humana.</div></div><span class="status status--warn">Em análise</span></div><div class="list-row"><div class="grow"><b>Pagamento divergente</b><div class="small muted">Exemplo: valor contestado.</div></div><span class="status status--warn">Em análise</span></div>`}
function workerModal(){modal(`<div class="notice">👤 Este pré-cadastro já é real: ele será salvo no Supabase.</div><h2>Quero trabalhar</h2><div class="form-grid"><div class="field"><label>Nome completo</label><input id="wName" placeholder="Seu nome"></div><div class="field"><label>WhatsApp</label><input id="wPhone" placeholder="(18) 99999-9999"></div><div class="field"><label>Área principal</label><select id="wRole"><option>Garçom</option><option>Barman</option><option>Auxiliar de cozinha</option><option>Churrasqueiro</option><option>Diarista</option><option>Limpeza</option><option>Recepção</option></select></div><div class="field"><label>Cidade</label><input id="wCity" value="Teodoro Sampaio"></div><div class="field"><label>Diária de referência</label><input id="wRate" inputmode="decimal" placeholder="150"></div><div class="field"><label>Transporte próprio</label><select id="wTransport"><option value="false">Não</option><option value="true">Sim</option></select></div><div class="field full"><label>Disponibilidade</label><input id="wAvailability" placeholder="Ex.: noites e fins de semana"></div><div class="field full"><label>Experiência</label><textarea id="wExperience" placeholder="Conte rapidamente sua experiência"></textarea></div></div><div class="modal-actions"><button class="btn btn--green" id="saveWorkerBtn" onclick="saveWorker()">Salvar e confirmar WhatsApp</button><button class="btn btn--outline" onclick="closeModal()">Cancelar</button></div>`)}
async function saveWorker(){const btn=$('saveWorkerBtn'),name=$('wName').value.trim(),phone=$('wPhone').value.trim(),city=$('wCity').value.trim()||'Teodoro Sampaio',role=$('wRole').value;if(name.length<2||phone.length<8){toast('Preencha nome e WhatsApp corretamente');return}btn.disabled=true;btn.textContent='Salvando...';try{const payload={full_name:name,whatsapp:phone,city,primary_role:role,experience:$('wExperience').value.trim()||null,reference_daily:$('wRate').value?Number($('wRate').value.replace(',','.')):null,has_transport:$('wTransport').value==='true',availability:$('wAvailability').value.trim()||null,whatsapp_confirmation_status:'pending',validation_status:'new',source:'vercel_free_stack'};const r=await apiPost('it_professional_signups',payload);if(!r.ok)throw new Error(await r.text());await loadMetrics();const msg=encodeURIComponent(`👋 Olá! Fiz meu pré-cadastro na *IntegraTrampo* e quero confirmar meu WhatsApp.\n\n👤 *Nome:* ${name}\n📱 *WhatsApp:* ${phone}\n📍 *Cidade:* ${city}\n💼 *Área:* ${role}\n\n✅ Quero validar meu cadastro.`);closeModal();toast('Cadastro salvo no Supabase');window.open(`https://wa.me/${WA_NUMBER}?text=${msg}`,'_blank')}catch(e){console.error(e);toast('Não foi possível salvar agora');btn.disabled=false;btn.textContent='Salvar e confirmar WhatsApp'}}
function hiringModal(){modal(`<div class="notice">🏢 Este pedido também será salvo no Supabase real.</div><h2>Preciso contratar</h2><div class="form-grid"><div class="field"><label>Empresa ou seu nome</label><input id="hName"></div><div class="field"><label>WhatsApp</label><input id="hPhone"></div><div class="field"><label>Tipo</label><select id="hType"><option value="company">Empresa</option><option value="person">Pessoa física</option></select></div><div class="field"><label>Cidade</label><input id="hCity" value="Teodoro Sampaio"></div><div class="field"><label>Profissional necessário</label><select id="hCat"><option>Garçom</option><option>Barman</option><option>Auxiliar de cozinha</option><option>Churrasqueiro</option><option>Limpeza</option></select></div><div class="field"><label>Vagas</label><input id="hVac" type="number" min="1" value="1"></div><div class="field"><label>Data</label><input id="hDate" type="date"></div><div class="field"><label>Valor por diária</label><input id="hRate" inputmode="decimal"></div><div class="field full"><label>Descrição</label><textarea id="hDesc" placeholder="Conte o que você precisa"></textarea></div></div><div class="modal-actions"><button class="btn btn--orange" id="saveHireBtn" onclick="saveHiring()">Enviar necessidade</button><button class="btn btn--outline" onclick="closeModal()">Cancelar</button></div>`)}
async function saveHiring(){const btn=$('saveHireBtn'),name=$('hName').value.trim(),phone=$('hPhone').value.trim();if(name.length<2||phone.length<8){toast('Preencha nome e WhatsApp corretamente');return}btn.disabled=true;btn.textContent='Enviando...';try{const payload={requester_name:name,whatsapp:phone,requester_type:$('hType').value,city:$('hCity').value.trim()||'Teodoro Sampaio',category:$('hCat').value,vacancies:Number($('hVac').value||1),service_date:$('hDate').value||null,daily_rate:$('hRate').value?Number($('hRate').value.replace(',','.')):null,description:$('hDesc').value.trim()||null,status:'new',source:'vercel_free_stack'};const r=await apiPost('it_hiring_requests',payload);if(!r.ok)throw new Error(await r.text());await loadMetrics();closeModal();toast('Pedido salvo no Supabase. Entraremos em contato.')}catch(e){console.error(e);toast('Não foi possível enviar agora');btn.disabled=false;btn.textContent='Enviar necessidade'}}
function notificationModal(){modal(`<h2>Notificações</h2><div class="list"><div class="list-row"><div class="grow"><b>Nova vaga compatível</b><div class="small muted">2 garçons · 96% match</div></div><span class="status status--ok">demo</span></div><div class="list-row"><div class="grow"><b>Cadastros reais ativos</b><div class="small muted">O Supabase já recebe pré-cadastros.</div></div><span class="status status--ok">online</span></div></div><div class="modal-actions"><button class="btn btn--outline" onclick="closeModal()">Fechar</button></div>`)}
function loginModal(){modal(`<div class="notice">🔐 Login real entra na próxima etapa com Supabase Auth.</div><h2>Entrar</h2><div class="form-grid"><div class="field full"><label>WhatsApp ou e-mail</label><input></div><div class="field full"><label>Senha</label><input type="password"></div></div><div class="modal-actions"><button class="btn btn--navy" onclick="closeModal();go('painel')">Entrar na demo</button><button class="btn btn--outline" onclick="closeModal()">Cancelar</button></div>`)}
function chatModal(){modal(`<div class="notice">💬 Chat demonstrativo. Mensagens reais entram depois do login.</div><h2>Espaço Aurora Eventos</h2><div class="chat"><div class="bubble">Olá! Vi sua candidatura para sábado.</div><div class="bubble me">Oi! Tenho disponibilidade sim 👍</div><div class="bubble">Perfeito. Depois das confirmações liberamos os detalhes finais.</div></div><div class="modal-actions"><button class="btn btn--green" onclick="toast('Mensagem demo enviada')">Enviar demo</button><button class="btn btn--outline" onclick="closeModal()">Fechar</button></div>`)}
function reviewModal(){modal(`<div class="notice">⭐ Avaliação bilateral demonstrativa.</div><h2>Avaliar serviço</h2><div class="form-grid"><div class="field"><label>Nota</label><select><option>5 — Excelente</option><option>4 — Muito bom</option><option>3 — Bom</option></select></div><div class="field"><label>Critério</label><select><option>Pontualidade</option><option>Comunicação</option><option>Pagamento</option></select></div><div class="field full"><label>Comentário</label><textarea></textarea></div></div><div class="modal-actions"><button class="btn btn--green" onclick="closeModal();toast('Avaliação demo salva')">Salvar</button><button class="btn btn--outline" onclick="closeModal()">Fechar</button></div>`)}
function apiGet(path){return fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:{apikey:SUPABASE_KEY}})}
function apiPost(table,payload){return fetch(`${SUPABASE_URL}/rest/v1/${table}`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify(payload)})}
async function loadMetrics(){try{const r=await apiGet('it_public_metrics_cache?key=eq.main&select=signups,hiring_requests,confirmed_whatsapp,approved_professionals,published_opportunities');if(r.ok){const d=await r.json();if(d[0])metrics=d[0]}}catch(e){console.warn(e)}$('metricSignups').textContent=metrics.signups;$('metricHiring').textContent=metrics.hiring_requests;$('metricConfirmed').textContent=metrics.confirmed_whatsapp;renderOps()}
async function loadPublicData(){try{const [pr,jb,co]=await Promise.all([apiGet('it_public_professionals?is_published=eq.true&select=id,display_name,role_title,city,reference_daily,has_transport,availability,rating,review_count,photo_url'),apiGet('it_opportunities?status=eq.published&select=id,title,category,city,service_date,start_time,end_time,daily_rate,vacancies,image_url,company_id'),apiGet('it_companies?is_published=eq.true&select=id,display_name,kind,city,rating,review_count,logo_url')]);if(pr.ok){publicPros=(await pr.json()).map(x=>({id:x.id,name:x.display_name,role:x.role_title,city:x.city,rate:Number(x.reference_daily)||null,rating:Number(x.rating)||0,reviews:x.review_count||0,match:90,tags:[x.has_transport?'Transporte':'Local',x.availability||'Disponível'],img:x.photo_url}))}if(co.ok){publicCompanies=(await co.json()).map(x=>({id:x.id,name:x.display_name,kind:x.kind||'Contratante',city:x.city,rating:Number(x.rating)||0,jobs:x.review_count||0,img:x.logo_url}))}if(jb.ok){const rows=await jb.json();publicJobs=rows.map(x=>({id:x.id,title:x.title,company:'Contratante verificado',cat:x.category,date:x.service_date||'A combinar',time:[x.start_time,x.end_time].filter(Boolean).join(' às ')||'A combinar',rate:Number(x.daily_rate)||null,v:x.vacancies||1,match:90,img:x.image_url}))}}catch(e){console.warn(e)}renderAll()}
function populateFilters(){const jc=[...new Set(currentJobs().map(x=>x.cat))],pc=[...new Set(currentPros().map(x=>x.role.split(' • ')[0]))];$('jobCategory').innerHTML='<option value="">Todas as categorias</option>'+jc.map(x=>`<option>${x}</option>`).join('');$('proCategory').innerHTML='<option value="">Todas as áreas</option>'+pc.map(x=>`<option>${x}</option>`).join('')}
function renderAll(){renderCategories();populateFilters();renderHome();renderPros();renderJobs();renderCompanies();renderPanel();renderOps()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-go]');if(b)go(b.dataset.go)});
$('workerBtn').onclick=workerModal;$('hireBtn').onclick=hiringModal;$('hireBtn2').onclick=hiringModal;$('notifyBtn').onclick=notificationModal;$('loginBtn').onclick=loginModal;$('chatBtn').onclick=chatModal;
$('jobQuery').oninput=renderJobs;$('jobCategory').onchange=renderJobs;$('jobOrder').onchange=renderJobs;$('clearJobs').onclick=()=>{$('jobQuery').value='';$('jobCategory').value='';$('jobOrder').value='match';renderJobs()};
$('proQuery').oninput=renderPros;$('proCategory').onchange=renderPros;$('proOrder').onchange=renderPros;$('clearPros').onclick=()=>{$('proQuery').value='';$('proCategory').value='';$('proOrder').value='match';renderPros()};
renderAll();loadMetrics();loadPublicData();