const SUPABASE_URL='https://ghspaqawzfqtsxibgqxy.supabase.co';
const SUPABASE_KEY='sb_publishable_zzfaJaBr-schcxD7EMh3wA_69Vx1Xsg';
const WA_NUMBER='5518981485892';
const categories=[['🍽️','Garçom'],['🍸','Barman'],['🧹','Diarista'],['🎨','Pintor'],['🧽','Faxineira'],['⚡','Eletricista'],['🌿','Jardineiro'],['🛡️','Segurança'],['•••','Outros']];
let publicPros=[],publicJobs=[],publicCompanies=[],metrics={signups:0,hiring_requests:0,confirmed_whatsapp:0,approved_professionals:0,published_opportunities:0};
let state=JSON.parse(localStorage.getItem('it_free_stack')||'{"fav":[]}');
const save=()=>localStorage.setItem('it_free_stack',JSON.stringify(state));
const $=id=>document.getElementById(id);
const emptyState=message=>`<div class="panel" style="grid-column:1/-1;text-align:center;padding:30px"><b>${message}</b></div>`;
function toast(msg){const el=document.createElement('div');el.className='toast';el.textContent=msg;$('toastRoot').appendChild(el);setTimeout(()=>el.remove(),2400)}
function go(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('is-active'));$('screen-'+id)?.classList.add('is-active');document.querySelectorAll('[data-nav]').forEach(x=>x.classList.toggle('is-active',x.dataset.nav===id));scrollTo({top:0,behavior:'smooth'});if(id==='painel')renderPanel();if(id==='operacao')renderOps()}
function modal(html){$('modalRoot').innerHTML=`<div class="modal-bg"><div class="modal">${html}</div></div>`;$('modalRoot').querySelector('.modal-bg').addEventListener('click',e=>{if(e.target.classList.contains('modal-bg'))closeModal()})}
function closeModal(){$('modalRoot').innerHTML=''}
function proCard(p){return `<article class="card"><div class="card__media"><img src="${p.img}" alt="Foto de ${p.name}"><span class="badge badge--green" style="position:absolute;left:12px;top:12px">PERFIL APROVADO</span></div><div class="card__body"><h3>${p.name}</h3><div class="muted small">${p.role}</div><div class="rating">⭐ ${p.rating||0} <span class="muted">(${p.reviews||0})</span></div><div class="tags">${(p.tags||[]).map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="money">${p.rate?`R$ ${p.rate}/dia`:'Valor a combinar'}</div><div class="card-actions"><button class="btn btn--outline" onclick="openPro('${p.id}')">Ver perfil</button></div></div></article>`}
function jobCard(o){const fav=state.fav.includes(o.id);return `<article class="card"><div class="card__media"><img src="${o.img||'https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1000&q=80'}" alt="Imagem da oportunidade"><span class="badge badge--green" style="position:absolute;left:12px;top:12px">VAGA PUBLICADA</span></div><div class="card__body"><div class="muted small">${o.company}</div><h3>${o.title}</h3><div class="meta"><span>📅 ${o.date||'A combinar'}</span><span>⏰ ${o.time||'A combinar'}</span></div><div class="money">${o.rate?`R$ ${o.rate}/dia`:'Valor a combinar'}</div><div class="card-actions"><button class="btn btn--green" onclick="openJob('${o.id}')">Ver vaga</button><button class="btn btn--outline fav" onclick="toggleFav('${o.id}')">${fav?'♥':'♡'}</button></div></div></article>`}
function companyCard(c){return `<article class="card company-card"><div class="company-head"><img class="company-photo" src="${c.img}" alt="Identificação visual de ${c.name}"><div><span class="badge badge--green">CADASTRO APROVADO</span><h3>${c.name}</h3><div class="muted small">${c.kind}</div></div></div><div class="meta"><span>⭐ ${c.rating||0}</span><span>${c.jobs||0} avaliações</span></div><button class="btn btn--outline" style="width:100%" onclick="openCompany('${c.id}')">Ver empresa</button></article>`}
function renderCategories(){$('categoryGrid').innerHTML=categories.map(([i,n])=>`<button class="category" onclick="filterCategory('${n}')"><span class="category__icon">${i}</span><b>${n}</b></button>`).join('')}
function renderHome(){$('homePros').innerHTML=publicPros.length?publicPros.slice(0,4).map(proCard).join(''):emptyState('Os primeiros profissionais aprovados aparecerão aqui.');$('homeJobs').innerHTML=publicJobs.length?publicJobs.slice(0,3).map(jobCard).join(''):emptyState('Ainda não há oportunidades publicadas.');$('homeCompanies').innerHTML=publicCompanies.length?publicCompanies.slice(0,4).map(companyCard).join(''):emptyState('Os primeiros contratantes aprovados aparecerão aqui.')}
function renderPros(){let q=($('proQuery')?.value||'').toLowerCase(),cat=$('proCategory')?.value||'',ord=$('proOrder')?.value||'match';let arr=publicPros.filter(p=>(!q||`${p.name} ${p.role} ${(p.tags||[]).join(' ')}`.toLowerCase().includes(q))&&(!cat||p.role.includes(cat)));arr.sort((a,b)=>ord==='rating'?(b.rating||0)-(a.rating||0):ord==='rate'?(a.rate||9999)-(b.rate||9999):a.name.localeCompare(b.name));$('proGrid').innerHTML=arr.length?arr.map(proCard).join(''):emptyState('Nenhum profissional publicado com esses filtros.')}
function renderJobs(){let q=($('jobQuery')?.value||'').toLowerCase(),cat=$('jobCategory')?.value||'',ord=$('jobOrder')?.value||'match';let arr=publicJobs.filter(o=>(!q||`${o.title} ${o.company} ${o.cat}`.toLowerCase().includes(q))&&(!cat||o.cat===cat));arr.sort((a,b)=>ord==='rate'?(b.rate||0)-(a.rate||0):a.title.localeCompare(b.title));$('jobGrid').innerHTML=arr.length?arr.map(jobCard).join(''):emptyState('Nenhuma oportunidade publicada com esses filtros.')}
function renderCompanies(){$('companyGrid').innerHTML=publicCompanies.length?publicCompanies.map(companyCard).join(''):emptyState('Nenhum contratante publicado ainda.')}
function toggleFav(id){const i=state.fav.indexOf(id);i>=0?state.fav.splice(i,1):state.fav.push(id);save();renderJobs();renderHome();toast(i>=0?'Removido dos favoritos':'Salvo nos favoritos')}
function filterCategory(cat){go('vagas');$('jobCategory').value=publicJobs.some(x=>x.cat===cat)?cat:'';renderJobs()}
function openPro(id){const p=publicPros.find(x=>x.id===id);if(!p)return;modal(`<div class="notice">✅ Perfil aprovado pela IntegraTrampo.</div><h2>${p.name}</h2><p class="muted">${p.role} · ${p.city||'Teodoro Sampaio - SP'}</p><div class="kpi-grid"><div class="kpi"><strong>${p.rating||0}</strong><span>Nota</span></div><div class="kpi"><strong>${p.reviews||0}</strong><span>Avaliações</span></div><div class="kpi"><strong>${p.rate?`R$ ${p.rate}`:'—'}</strong><span>Diária</span></div><div class="kpi"><strong>${p.has_transport?'Sim':'—'}</strong><span>Transporte</span></div></div><div class="modal-actions"><button class="btn btn--green" onclick="loginModal()">Tenho interesse</button><button class="btn btn--outline" onclick="closeModal()">Fechar</button></div>`)}
function openCompany(id){const c=publicCompanies.find(x=>x.id===id);if(!c)return;modal(`<div class="notice">✅ Contratante aprovado pela IntegraTrampo.</div><h2>${c.name}</h2><p class="muted">${c.kind} · ${c.city||'Teodoro Sampaio - SP'}</p><div class="kpi-grid"><div class="kpi"><strong>${c.rating||0}</strong><span>Reputação</span></div><div class="kpi"><strong>${c.jobs||0}</strong><span>Avaliações</span></div><div class="kpi"><strong>Local</strong><span>Atuação</span></div><div class="kpi"><strong>✅</strong><span>Cadastro</span></div></div><button class="btn btn--outline" onclick="closeModal()">Fechar</button>`)}
function openJob(id){const o=publicJobs.find(x=>x.id===id);if(!o)return;modal(`<div class="notice">💼 Oportunidade publicada e aprovada.</div><h2>${o.title}</h2><p class="muted">${o.company} · ${o.cat}</p><div class="meta"><span>📅 ${o.date||'A combinar'}</span><span>⏰ ${o.time||'A combinar'}</span><span>👥 ${o.v||1} vaga(s)</span></div><div class="money">${o.rate?`R$ ${o.rate}/dia`:'Valor a combinar'}</div><div class="modal-actions"><button class="btn btn--green" onclick="loginModal()">Tenho interesse</button><button class="btn btn--outline" onclick="closeModal()">Fechar</button></div>`)}
function renderPanel(){$('panelKpis').innerHTML=`<article class="kpi"><strong>🔐</strong><span>Acesso individual</span></article><article class="kpi"><strong>💼</strong><span>Candidaturas</span></article><article class="kpi"><strong>🤝</strong><span>Serviços</span></article><article class="kpi"><strong>⭐</strong><span>Avaliações</span></article>`;$('serviceFlow').innerHTML=`<div class="list-row"><div class="grow"><b>Entre para acessar seu painel</b><div class="small muted">O acesso individual será usado para candidaturas, confirmações de serviço e avaliações.</div></div><button class="btn btn--navy" onclick="loginModal()">Entrar</button></div>`;$('candidateList').innerHTML=`<div class="list-row"><div class="grow"><b>Seus dados ficam protegidos</b><div class="small muted">Informações pessoais não são exibidas neste painel público.</div></div><span class="status status--ok">RLS ativo</span></div>`}
function renderOps(){$('opsKpis').innerHTML=[[metrics.signups,'Pré-cadastros'],[metrics.hiring_requests,'Pedidos de contratação'],[metrics.confirmed_whatsapp,'WhatsApps confirmados'],[metrics.approved_professionals,'Perfis publicados']].map(k=>`<article class="kpi"><strong>${k[0]}</strong><span>${k[1]}</span></article>`).join('');$('opsQueue').innerHTML=`<div class="list-row"><div class="grow"><b>Foto obrigatória para profissionais</b><div class="small muted">Um perfil só pode ser aprovado e publicado depois de receber uma foto adequada.</div></div><span class="status status--ok">Obrigatória</span></div><div class="list-row"><div class="grow"><b>Identificação visual do contratante</b><div class="small muted">Empresas precisam de logo ou foto; contratantes pessoa física terão identificação própria antes da ativação pública.</div></div><span class="status status--ok">Obrigatória</span></div><div class="list-row"><div class="grow"><b>Confirmação manual de WhatsApp</b><div class="small muted">Mantida no piloto para evitar custos de SMS e serviços externos.</div></div><span class="status status--wait">Operação</span></div>`;$('incidentList').innerHTML=`<div class="list-row"><div class="grow"><b>Incidentes são privados</b><div class="small muted">Relatos de no-show, pagamento, segurança ou comportamento são revisados pela operação e não geram punição automática.</div></div><span class="status status--ok">Revisão humana</span></div>`}
function workerModal(){modal(`<div class="notice">👤 Seu pré-cadastro será salvo com segurança no Supabase.</div><div class="notice">📸 <b>Foto obrigatória para ativação.</b> Você pode concluir o pré-cadastro agora. Depois de confirmar o WhatsApp, envie uma foto de perfil nítida. O perfil só será publicado após a aprovação da foto.</div><h2>Quero trabalhar</h2><div class="form-grid"><div class="field"><label>Nome completo</label><input id="wName" placeholder="Seu nome"></div><div class="field"><label>WhatsApp</label><input id="wPhone" placeholder="(18) 99999-9999"></div><div class="field"><label>Área principal</label><select id="wRole"><option>Garçom</option><option>Barman</option><option>Auxiliar de cozinha</option><option>Churrasqueiro</option><option>Diarista</option><option>Limpeza</option><option>Recepção</option><option>Segurança</option></select></div><div class="field"><label>Cidade</label><input id="wCity" value="Teodoro Sampaio"></div><div class="field"><label>Diária de referência</label><input id="wRate" inputmode="decimal" placeholder="150"></div><div class="field"><label>Transporte próprio</label><select id="wTransport"><option value="false">Não</option><option value="true">Sim</option></select></div><div class="field full"><label>Disponibilidade</label><input id="wAvailability" placeholder="Ex.: noites e fins de semana"></div><div class="field full"><label>Experiência</label><textarea id="wExperience" placeholder="Conte rapidamente sua experiência"></textarea></div></div><div class="modal-actions"><button class="btn btn--green" id="saveWorkerBtn" onclick="saveWorker()">Salvar e confirmar WhatsApp</button><button class="btn btn--outline" onclick="closeModal()">Cancelar</button></div>`)}
async function saveWorker(){const btn=$('saveWorkerBtn'),name=$('wName').value.trim(),phone=$('wPhone').value.trim(),city=$('wCity').value.trim()||'Teodoro Sampaio',role=$('wRole').value;if(name.length<2||phone.length<8){toast('Preencha nome e WhatsApp corretamente');return}btn.disabled=true;btn.textContent='Salvando...';try{const payload={full_name:name,whatsapp:phone,city,primary_role:role,experience:$('wExperience').value.trim()||null,reference_daily:$('wRate').value?Number($('wRate').value.replace(',','.')):null,has_transport:$('wTransport').value==='true',availability:$('wAvailability').value.trim()||null,whatsapp_confirmation_status:'pending',validation_status:'new',photo_status:'pending',source:'vercel_free_stack'};const r=await apiPost('it_professional_signups',payload);if(!r.ok)throw new Error(await r.text());await loadMetrics();const msg=encodeURIComponent(`👋 Olá! Fiz meu pré-cadastro na *IntegraTrampo* e quero confirmar meu WhatsApp.\n\n👤 *Nome:* ${name}\n📱 *WhatsApp:* ${phone}\n📍 *Cidade:* ${city}\n💼 *Área:* ${role}\n\n✅ Quero validar meu cadastro.\n📸 Sei que a foto de perfil é obrigatória para ativação e vou enviar uma foto nítida nesta conversa.`);closeModal();toast('Cadastro recebido');window.open(`https://wa.me/${WA_NUMBER}?text=${msg}`,'_blank')}catch(e){console.error(e);toast('Não foi possível salvar agora');btn.disabled=false;btn.textContent='Salvar e confirmar WhatsApp'}}
function hiringModal(){modal(`<div class="notice">🏢 Seu pedido será salvo com segurança no Supabase.</div><div class="notice">📸 Antes de um contratante aparecer publicamente na plataforma, a identificação visual também será obrigatória.</div><h2>Preciso contratar</h2><div class="form-grid"><div class="field"><label>Empresa ou seu nome</label><input id="hName"></div><div class="field"><label>WhatsApp</label><input id="hPhone"></div><div class="field"><label>Tipo</label><select id="hType"><option value="company">Empresa</option><option value="person">Pessoa física</option></select></div><div class="field"><label>Cidade</label><input id="hCity" value="Teodoro Sampaio"></div><div class="field"><label>Profissional necessário</label><select id="hCat"><option>Garçom</option><option>Barman</option><option>Auxiliar de cozinha</option><option>Churrasqueiro</option><option>Limpeza</option><option>Segurança</option></select></div><div class="field"><label>Vagas</label><input id="hVac" type="number" min="1" value="1"></div><div class="field"><label>Data</label><input id="hDate" type="date"></div><div class="field"><label>Valor por diária</label><input id="hRate" inputmode="decimal"></div><div class="field full"><label>Descrição</label><textarea id="hDesc" placeholder="Conte o que você precisa"></textarea></div></div><div class="modal-actions"><button class="btn btn--orange" id="saveHireBtn" onclick="saveHiring()">Enviar necessidade</button><button class="btn btn--outline" onclick="closeModal()">Cancelar</button></div>`)}
async function saveHiring(){const btn=$('saveHireBtn'),name=$('hName').value.trim(),phone=$('hPhone').value.trim();if(name.length<2||phone.length<8){toast('Preencha nome e WhatsApp corretamente');return}btn.disabled=true;btn.textContent='Enviando...';try{const payload={requester_name:name,whatsapp:phone,requester_type:$('hType').value,city:$('hCity').value.trim()||'Teodoro Sampaio',category:$('hCat').value,vacancies:Number($('hVac').value||1),service_date:$('hDate').value||null,daily_rate:$('hRate').value?Number($('hRate').value.replace(',','.')):null,description:$('hDesc').value.trim()||null,status:'new',source:'vercel_free_stack'};const r=await apiPost('it_hiring_requests',payload);if(!r.ok)throw new Error(await r.text());await loadMetrics();closeModal();toast('Pedido recebido. Entraremos em contato.')}catch(e){console.error(e);toast('Não foi possível enviar agora');btn.disabled=false;btn.textContent='Enviar necessidade'}}
function notificationModal(){modal(`<h2>Notificações</h2><div class="list"><div class="list-row"><div class="grow"><b>Fase piloto ativa</b><div class="small muted">Pré-cadastros e pedidos de contratação já são recebidos pelo Supabase.</div></div><span class="status status--ok">online</span></div><div class="list-row"><div class="grow"><b>Foto obrigatória</b><div class="small muted">Perfis profissionais não são publicados sem foto aprovada.</div></div><span class="status status--ok">ativa</span></div></div><div class="modal-actions"><button class="btn btn--outline" onclick="closeModal()">Fechar</button></div>`)}
function loginModal(){closeModal();modal(`<div class="notice">🔐 O acesso individual está sendo ativado com Supabase Auth.</div><h2>Entrar</h2><p class="muted">Enquanto o acesso individual não é liberado, você já pode fazer o pré-cadastro profissional ou enviar uma necessidade de contratação.</p><div class="modal-actions"><button class="btn btn--green" onclick="closeModal();workerModal()">Quero trabalhar</button><button class="btn btn--orange" onclick="closeModal();hiringModal()">Preciso contratar</button><button class="btn btn--outline" onclick="closeModal()">Fechar</button></div>`)}
function apiGet(path){return fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:{apikey:SUPABASE_KEY}})}
function apiPost(table,payload){return fetch(`${SUPABASE_URL}/rest/v1/${table}`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify(payload)})}
async function loadMetrics(){try{const r=await apiGet('it_public_metrics_cache?key=eq.main&select=signups,hiring_requests,confirmed_whatsapp,approved_professionals,published_opportunities');if(r.ok){const d=await r.json();if(d[0])metrics=d[0]}}catch(e){console.warn(e)}$('metricSignups').textContent=metrics.signups;$('metricHiring').textContent=metrics.hiring_requests;$('metricConfirmed').textContent=metrics.confirmed_whatsapp;$('metricApproved').textContent=metrics.approved_professionals;renderOps()}
async function loadPublicData(){try{const [pr,jb,co]=await Promise.all([apiGet('it_public_professionals?is_published=eq.true&select=id,display_name,role_title,city,reference_daily,has_transport,availability,rating,review_count,photo_url'),apiGet('it_opportunities?status=eq.published&select=id,title,category,city,service_date,start_time,end_time,daily_rate,vacancies,image_url,company_id'),apiGet('it_companies?is_published=eq.true&select=id,display_name,kind,city,rating,review_count,logo_url')]);if(pr.ok){publicPros=(await pr.json()).filter(x=>x.photo_url).map(x=>({id:x.id,name:x.display_name,role:x.role_title,city:x.city,rate:Number(x.reference_daily)||null,rating:Number(x.rating)||0,reviews:x.review_count||0,tags:[x.has_transport?'Transporte':'Local',x.availability||'Disponível'],img:x.photo_url,has_transport:x.has_transport}))}if(co.ok){publicCompanies=(await co.json()).filter(x=>x.logo_url).map(x=>({id:x.id,name:x.display_name,kind:x.kind||'Contratante',city:x.city,rating:Number(x.rating)||0,jobs:x.review_count||0,img:x.logo_url}))}if(jb.ok){const rows=await jb.json();publicJobs=rows.map(x=>({id:x.id,title:x.title,company:'Contratante aprovado',cat:x.category,date:x.service_date||'A combinar',time:[x.start_time,x.end_time].filter(Boolean).join(' às ')||'A combinar',rate:Number(x.daily_rate)||null,v:x.vacancies||1,img:x.image_url}))}}catch(e){console.warn(e)}renderAll()}
function populateFilters(){const jc=[...new Set(publicJobs.map(x=>x.cat))],pc=[...new Set(publicPros.map(x=>x.role.split(' • ')[0]))];$('jobCategory').innerHTML='<option value="">Todas as categorias</option>'+jc.map(x=>`<option>${x}</option>`).join('');$('proCategory').innerHTML='<option value="">Todas as áreas</option>'+pc.map(x=>`<option>${x}</option>`).join('')}
function renderAll(){renderCategories();populateFilters();renderHome();renderPros();renderJobs();renderCompanies();renderPanel();renderOps()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-go]');if(b)go(b.dataset.go)});
$('workerBtn').onclick=workerModal;$('hireBtn').onclick=hiringModal;$('hireBtn2').onclick=hiringModal;$('notifyBtn').onclick=notificationModal;$('loginBtn').onclick=loginModal;
$('jobQuery').oninput=renderJobs;$('jobCategory').onchange=renderJobs;$('jobOrder').onchange=renderJobs;$('clearJobs').onclick=()=>{$('jobQuery').value='';$('jobCategory').value='';$('jobOrder').value='match';renderJobs()};
$('proQuery').oninput=renderPros;$('proCategory').onchange=renderPros;$('proOrder').onchange=renderPros;$('clearPros').onclick=()=>{$('proQuery').value='';$('proCategory').value='';$('proOrder').value='match';renderPros()};
renderAll();loadMetrics();loadPublicData();
