// IntegraTrampo · acabamento premium
// Busca avançada, filtros inteligentes, páginas públicas ricas, home personalizada e SEO dinâmico.
(function(){
  let sb=null,currentUser=null,preferenceMode='both',initialized=false;
  let companySearch='',companyOrder='rating',proAvailability='',proMaxRate='',proTransport='',jobWhen='',jobMinRate='';
  const oldRenderHome=window.renderHome,oldRenderPros=window.renderPros,oldRenderJobs=window.renderJobs,oldRenderCompanies=window.renderCompanies;
  const oldOpenPro=window.openPro,oldOpenJob=window.openJob,oldOpenCompany=window.openCompany;
  const $id=id=>document.getElementById(id);
  const wait=ms=>new Promise(r=>setTimeout(r,ms));
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const normalize=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
  const money=v=>v===null||v===undefined||v===''?'A combinar':`R$ ${Number(v).toLocaleString('pt-BR',{maximumFractionDigits:2})}`;
  const isReal=id=>!/^(sample-|demo-)/.test(String(id||''));
  const today=()=>{const d=new Date();d.setHours(0,0,0,0);return d};
  const parseDate=v=>{if(!v||!/^\d{4}-\d{2}-\d{2}$/.test(String(v)))return null;const d=new Date(v+'T12:00:00');return Number.isNaN(d.getTime())?null:d};
  const daysFromToday=v=>{const d=parseDate(v);if(!d)return null;return Math.floor((d-today())/86400000)};
  const dateLabel=v=>{const n=daysFromToday(v);if(n===0)return 'Hoje';if(n===1)return 'Amanhã';if(n!==null&&n>1&&n<=7)return `Em ${n} dias`;try{return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(parseDate(v)||new Date(v))}catch{return v||'A combinar'}};
  const availability=v=>({available_today:['🟢','Disponível hoje'],available_week:['🟡','Disponível esta semana'],unavailable:['⚪','Indisponível']}[v]||['⚪','Disponibilidade não informada']);

  function injectStyles(){
    if($id('integratrampoPremiumStyles'))return;
    const s=document.createElement('style');s.id='integratrampoPremiumStyles';s.textContent=`
      .premium-filter{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.premium-filter select,.premium-filter input{min-height:42px;border:1px solid #d7e0e9;background:#fff;border-radius:12px;padding:0 11px;color:#0D1B2A;font:inherit}.premium-filter input{width:150px}.premium-results{font-size:12px;color:#687481;margin:9px 0 0}.premium-personal{display:grid;grid-template-columns:1.3fr .7fr;gap:16px;background:linear-gradient(135deg,#0D1B2A,#173754);color:#fff;border-radius:22px;padding:20px;margin:22px 0 8px;box-shadow:0 16px 40px rgba(13,27,42,.14)}.premium-personal h2{margin:4px 0 7px;font-size:22px}.premium-personal p{margin:0;color:#d9e4ef}.premium-personal__actions{display:flex;gap:8px;align-items:center;justify-content:flex-end;flex-wrap:wrap}.premium-personal .btn--outline{background:rgba(255,255,255,.08);border-color:rgba(255,255,255,.3);color:#fff}.premium-pill{display:inline-flex;align-items:center;gap:5px;border-radius:999px;padding:5px 9px;font-size:12px;font-weight:900;background:#eef8f5;color:#087858}.premium-pill--warm{background:#fff3eb;color:#b54b1c}.premium-card-note{font-size:12px;color:#66717d;margin-top:8px}.premium-detail-hero{display:flex;gap:14px;align-items:center;margin:8px 0 14px}.premium-detail-hero img{width:92px;height:92px;object-fit:cover;border-radius:20px;background:#eef2f6}.premium-detail-hero h2{margin:0 0 4px}.premium-detail-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin:13px 0}.premium-detail-box{background:#f5f8fb;border-radius:14px;padding:12px}.premium-detail-box strong{display:block;color:#0D1B2A;font-size:16px}.premium-detail-box span{font-size:12px;color:#687481}.premium-company-search{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0 16px}.premium-company-search input{flex:1;min-width:210px;min-height:44px;border:1px solid #d7e0e9;border-radius:12px;padding:0 12px;font:inherit}.premium-company-search select{min-height:44px;border:1px solid #d7e0e9;border-radius:12px;padding:0 10px;background:#fff}.premium-smart-tag{display:inline-flex;align-items:center;border-radius:999px;padding:4px 7px;background:#f0f5fa;color:#52616f;font-size:11px;font-weight:800}.premium-smart-tag--hot{background:#fff0e9;color:#b64b20}.premium-smart-tag--green{background:#e9fbf5;color:#087858}
      @media(max-width:700px){.premium-personal{grid-template-columns:1fr}.premium-personal__actions{justify-content:flex-start}.premium-detail-grid{grid-template-columns:1fr 1fr}.premium-filter>*{flex:1;min-width:140px}.premium-filter input{width:auto}}
    `;document.head.appendChild(s);
  }

  function updateSeo(title,description){
    document.title=title;
    const d=description||'IntegraTrampo conecta profissionais, vagas e contratantes locais em Teodoro Sampaio - SP.';
    const desc=document.querySelector('meta[name="description"]');if(desc)desc.content=d;
    const set=(attr,name,value)=>{let el=document.querySelector(`meta[${attr}="${name}"]`);if(!el){el=document.createElement('meta');el.setAttribute(attr,name);document.head.appendChild(el)}el.setAttribute('content',value)};
    set('property','og:title',title);set('property','og:description',d);set('name','twitter:title',title);set('name','twitter:description',d);
  }

  async function enrichPublicData(){
    if(!sb)return;
    try{
      const [prosRes,jobsRes,companiesRes]=await Promise.all([
        sb.from('it_public_professionals').select('id,bio,neighborhood,availability_status,availability_updated_at').eq('is_published',true),
        sb.from('it_opportunities').select('id,company_id,description,city,service_date,start_time,end_time,daily_rate,vacancies').eq('status','published'),
        sb.from('it_companies').select('id,display_name,kind,city,description,logo_url,rating,review_count').eq('is_published',true)
      ]);
      if(!prosRes.error&&typeof publicPros!=='undefined')for(const r of prosRes.data||[]){const p=publicPros.find(x=>String(x.id)===String(r.id));if(p)Object.assign(p,{bio:r.bio,neighborhood:r.neighborhood,availability_status:r.availability_status,availability_updated_at:r.availability_updated_at})}
      if(!companiesRes.error&&typeof publicCompanies!=='undefined')for(const r of companiesRes.data||[]){const c=publicCompanies.find(x=>String(x.id)===String(r.id));if(c)Object.assign(c,{description:r.description,city:r.city||c.city,kind:r.kind||c.kind,rating:Number(r.rating)||c.rating,reviews:r.review_count||c.jobs})}
      if(!jobsRes.error&&typeof publicJobs!=='undefined')for(const r of jobsRes.data||[]){const j=publicJobs.find(x=>String(x.id)===String(r.id));if(j){const c=(typeof publicCompanies!=='undefined'?publicCompanies:[]).find(x=>String(x.id)===String(r.company_id));Object.assign(j,{company_id:r.company_id,company:c?.name||j.company,description:r.description,city:r.city,service_date:r.service_date,start_time:r.start_time,end_time:r.end_time,rate:Number(r.daily_rate)||j.rate,v:r.vacancies||j.v});}}
    }catch(e){console.warn('premium enrich',e)}
  }

  function installExtraFilters(){
    const proBar=$id('proQuery')?.closest('.searchbar');if(proBar&&!$id('premiumProFilters')){const x=document.createElement('div');x.id='premiumProFilters';x.className='premium-filter';x.innerHTML=`<select id="proAvailability"><option value="">Qualquer disponibilidade</option><option value="available_today">🟢 Disponível hoje</option><option value="available_week">🟡 Esta semana</option><option value="unavailable">⚪ Indisponível</option></select><select id="proTransport"><option value="">Com ou sem transporte</option><option value="yes">🚗 Com transporte</option><option value="no">Sem transporte</option></select><input id="proMaxRate" inputmode="decimal" placeholder="Diária até R$"><span id="proResultCount" class="premium-results"></span>`;proBar.insertAdjacentElement('afterend',x);$id('proAvailability').onchange=e=>{proAvailability=e.target.value;renderPros()};$id('proTransport').onchange=e=>{proTransport=e.target.value;renderPros()};$id('proMaxRate').oninput=e=>{proMaxRate=e.target.value;renderPros()}}
    const jobBar=$id('jobQuery')?.closest('.searchbar');if(jobBar&&!$id('premiumJobFilters')){const x=document.createElement('div');x.id='premiumJobFilters';x.className='premium-filter';x.innerHTML=`<select id="jobWhen"><option value="">Qualquer data</option><option value="today">Hoje</option><option value="7">Próximos 7 dias</option><option value="30">Próximos 30 dias</option></select><input id="jobMinRate" inputmode="decimal" placeholder="Diária mínima R$"><span id="jobResultCount" class="premium-results"></span>`;jobBar.insertAdjacentElement('afterend',x);$id('jobWhen').onchange=e=>{jobWhen=e.target.value;renderJobs()};$id('jobMinRate').oninput=e=>{jobMinRate=e.target.value;renderJobs()}}
    const companyGrid=$id('companyGrid');if(companyGrid&&!$id('premiumCompanySearch')){const x=document.createElement('div');x.id='premiumCompanySearch';x.className='premium-company-search';x.innerHTML=`<input id="companyQuery" placeholder="Buscar empresa, tipo ou cidade" autocomplete="off"><select id="companyOrder"><option value="rating">Melhor reputação</option><option value="name">Nome A–Z</option></select><button class="btn btn--outline" id="clearCompanies">Limpar</button>`;companyGrid.parentElement.insertBefore(x,companyGrid);$id('companyQuery').oninput=e=>{companySearch=e.target.value;renderCompanies()};$id('companyOrder').onchange=e=>{companyOrder=e.target.value;renderCompanies()};$id('clearCompanies').onclick=()=>{companySearch='';companyOrder='rating';$id('companyQuery').value='';$id('companyOrder').value='rating';renderCompanies()}}
  }

  function proScore(p,q){let s=0;if(p.availability_status==='available_today')s+=30;else if(p.availability_status==='available_week')s+=18;s+=(Number(p.rating)||0)*8;s+=Math.min(Number(p.reviews)||0,20);if(q&&normalize(`${p.name} ${p.role}`).includes(q))s+=35;if(p.has_transport)s+=5;return s}
  function jobScore(j,q){let s=0;const d=daysFromToday(j.service_date||j.date);if(d===0)s+=35;else if(d!==null&&d>0&&d<=7)s+=25;s+=(Number(j.rate)||0)/10;if(q&&normalize(`${j.title} ${j.company} ${j.cat}`).includes(q))s+=30;return s}

  function premiumProCard(p,isSample=false){if(isSample&&typeof sampleProCard==='function')return sampleProCard(p);const av=availability(p.availability_status);return `<article class="card"><div class="card__media"><img src="${esc(p.img)}" alt="Foto de ${esc(p.name)}"><span class="badge badge--green" style="position:absolute;left:12px;top:12px">PERFIL APROVADO</span></div><div class="card__body"><div style="display:flex;justify-content:space-between;gap:8px;align-items:flex-start"><div><h3>${esc(p.name)}</h3><div class="muted small">${esc(p.role)}</div></div><span class="premium-smart-tag ${p.availability_status==='available_today'?'premium-smart-tag--green':''}">${av[0]} ${av[1]}</span></div><div class="rating">⭐ ${Number(p.rating||0)} <span class="muted">(${Number(p.reviews||0)})</span></div><div class="tags">${(p.tags||[]).slice(0,3).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><div class="money">${p.rate?`${money(p.rate)}/dia`:'Valor a combinar'}</div><div class="premium-card-note">📍 ${esc(p.city||'Teodoro Sampaio - SP')}${p.has_transport?' · 🚗 transporte próprio':''}</div><div class="card-actions"><button class="btn btn--outline" onclick="openPro('${esc(p.id)}')">Ver perfil</button><button class="btn btn--outline user-fav-btn" onclick="event.stopPropagation();toggleProfessionalFavorite?.('${esc(p.id)}')">♡</button></div></div></article>`}
  function premiumJobCard(j,isSample=false){if(isSample&&typeof sampleJobCard==='function')return sampleJobCard(j);const d=daysFromToday(j.service_date||j.date),hot=d!==null&&d>=0&&d<=2;return `<article class="card"><div class="card__media"><img src="${esc(j.img||'https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1000&q=80')}" alt="Imagem da oportunidade"><span class="badge badge--green" style="position:absolute;left:12px;top:12px">VAGA PUBLICADA</span></div><div class="card__body"><div class="muted small">${esc(j.company||'Contratante aprovado')}</div><div style="display:flex;justify-content:space-between;gap:8px"><h3>${esc(j.title)}</h3>${hot?'<span class="premium-smart-tag premium-smart-tag--hot">🔥 Em breve</span>':''}</div><div class="meta"><span>📅 ${esc(dateLabel(j.service_date||j.date))}</span><span>⏰ ${esc(j.time||'A combinar')}</span><span>👥 ${Number(j.v||1)} vaga(s)</span></div><div class="money">${j.rate?`${money(j.rate)}/dia`:'Valor a combinar'}</div><div class="premium-card-note">📍 ${esc(j.city||'Teodoro Sampaio - SP')}</div><div class="card-actions"><button class="btn btn--green" onclick="openJob('${esc(j.id)}')">Ver vaga</button><button class="btn btn--outline fav" onclick="toggleFav('${esc(j.id)}')">♡</button></div></div></article>`}

  window.renderPros=function(){
    const q=normalize($id('proQuery')?.value||''),cat=$id('proCategory')?.value||'',ord=$id('proOrder')?.value||'match',max=Number(String(proMaxRate||'').replace(',','.'))||null;
    let real=(typeof publicPros!=='undefined'?publicPros:[]).filter(p=>(!q||normalize(`${p.name} ${p.role} ${(p.tags||[]).join(' ')} ${p.city||''} ${p.availability||''}`).includes(q))&&(!cat||p.role.includes(cat))&&(!proAvailability||p.availability_status===proAvailability)&&(!proTransport||(proTransport==='yes'?!!p.has_transport:!p.has_transport))&&(!max||!p.rate||Number(p.rate)<=max));
    let samples=(typeof samplePros!=='undefined'?samplePros:[]).filter(p=>(!q||normalize(`${p.name} ${p.role} ${(p.tags||[]).join(' ')} ${p.city||''}`).includes(q))&&(!cat||p.role.includes(cat))&&!proAvailability&&!proTransport&&(!max||Number(p.rate)<=max));
    const sorter=ord==='rating'?((a,b)=>(b.rating||0)-(a.rating||0)):ord==='rate'?((a,b)=>(a.rate||999999)-(b.rate||999999)):((a,b)=>proScore(b,q)-proScore(a,q));real.sort(sorter);samples.sort(sorter);
    $id('proGrid').innerHTML=[...real.map(p=>premiumProCard(p)),...samples.map(p=>premiumProCard(p,true))].join('')||emptyState('Nenhum profissional encontrado com esses filtros.');if($id('proResultCount'))$id('proResultCount').textContent=`${real.length+samples.length} resultado(s)`;
  };

  window.renderJobs=function(){
    const q=normalize($id('jobQuery')?.value||''),cat=$id('jobCategory')?.value||'',ord=$id('jobOrder')?.value||'match',min=Number(String(jobMinRate||'').replace(',','.'))||null;
    const timeOk=j=>{if(!jobWhen)return true;const d=daysFromToday(j.service_date||j.date);if(d===null)return false;if(jobWhen==='today')return d===0;return d>=0&&d<=Number(jobWhen)};
    let real=(typeof publicJobs!=='undefined'?publicJobs:[]).filter(j=>(!q||normalize(`${j.title} ${j.company} ${j.cat} ${j.city||''} ${j.description||''}`).includes(q))&&(!cat||j.cat===cat)&&timeOk(j)&&(!min||Number(j.rate||0)>=min));
    let samples=(typeof sampleJobs!=='undefined'?sampleJobs:[]).filter(j=>(!q||normalize(`${j.title} ${j.company} ${j.cat}`).includes(q))&&(!cat||j.cat===cat)&&!jobWhen&&(!min||Number(j.rate||0)>=min));
    const sorter=ord==='rate'?((a,b)=>(b.rate||0)-(a.rate||0)):((a,b)=>jobScore(b,q)-jobScore(a,q));real.sort(sorter);samples.sort(sorter);
    $id('jobGrid').innerHTML=[...real.map(j=>premiumJobCard(j)),...samples.map(j=>premiumJobCard(j,true))].join('')||emptyState('Nenhuma oportunidade encontrada com esses filtros.');if($id('jobResultCount'))$id('jobResultCount').textContent=`${real.length+samples.length} resultado(s)`;
  };

  window.renderCompanies=function(){
    const q=normalize(companySearch);let real=(typeof publicCompanies!=='undefined'?publicCompanies:[]).filter(c=>!q||normalize(`${c.name} ${c.kind||''} ${c.city||''} ${c.description||''}`).includes(q));let samples=(typeof sampleCompanies!=='undefined'?sampleCompanies:[]).filter(c=>!q||normalize(`${c.name} ${c.kind||''} ${c.city||''}`).includes(q));const sorter=companyOrder==='name'?((a,b)=>a.name.localeCompare(b.name,'pt-BR')):((a,b)=>(b.rating||0)-(a.rating||0));real.sort(sorter);samples.sort(sorter);$id('companyGrid').innerHTML=[...real.map(companyCard),...samples.map(sampleCompanyCard)].join('')||emptyState('Nenhum contratante encontrado.');
  };

  function installResetHooks(){
    const oldClearPros=$id('clearPros')?.onclick;$id('clearPros')&&($id('clearPros').onclick=()=>{if(oldClearPros)oldClearPros();proAvailability='';proMaxRate='';proTransport='';if($id('proAvailability'))$id('proAvailability').value='';if($id('proMaxRate'))$id('proMaxRate').value='';if($id('proTransport'))$id('proTransport').value='';renderPros()});
    const oldClearJobs=$id('clearJobs')?.onclick;$id('clearJobs')&&($id('clearJobs').onclick=()=>{if(oldClearJobs)oldClearJobs();jobWhen='';jobMinRate='';if($id('jobWhen'))$id('jobWhen').value='';if($id('jobMinRate'))$id('jobMinRate').value='';renderJobs()});
  }

  window.openPro=function(id){if(!isReal(id))return oldOpenPro?.(id);const p=(typeof publicPros!=='undefined'?publicPros:[]).find(x=>String(x.id)===String(id));if(!p)return oldOpenPro?.(id);const av=availability(p.availability_status);updateSeo(`${p.name} · ${p.role} | IntegraTrampo`,`${p.name} atua como ${p.role} em ${p.city||'Teodoro Sampaio'}. Perfil profissional aprovado na IntegraTrampo.`);modal(`<div class="notice">✅ <b>Perfil real aprovado pela IntegraTrampo.</b></div><div class="premium-detail-hero"><img src="${esc(p.img)}" alt="Foto de ${esc(p.name)}"><div><h2>${esc(p.name)}</h2><div class="muted">${esc(p.role)} · ${esc(p.city||'Teodoro Sampaio - SP')}</div><div style="margin-top:7px"><span class="premium-pill">${av[0]} ${av[1]}</span></div></div></div>${p.bio?`<p>${esc(p.bio)}</p>`:''}<div class="premium-detail-grid"><div class="premium-detail-box"><strong>⭐ ${Number(p.rating||0)}</strong><span>${Number(p.reviews||0)} avaliações</span></div><div class="premium-detail-box"><strong>${p.rate?money(p.rate):'A combinar'}</strong><span>diária de referência</span></div><div class="premium-detail-box"><strong>${p.has_transport?'Sim':'Não'}</strong><span>transporte próprio</span></div></div><div class="tags">${(p.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><div class="modal-actions"><button class="btn btn--green" onclick="closeModal();hiringModal()">Quero contratar</button><button class="btn btn--outline" onclick="toggleProfessionalFavorite?.('${esc(id)}')">♡ Favoritar</button><button class="btn btn--outline" onclick="shareIntegraTrampo?.('pro','${esc(id)}')">Compartilhar</button><button class="btn btn--outline" onclick="closeModal()">Fechar</button></div>`)};

  window.openJob=function(id){if(!isReal(id))return oldOpenJob?.(id);const j=(typeof publicJobs!=='undefined'?publicJobs:[]).find(x=>String(x.id)===String(id));if(!j)return oldOpenJob?.(id);updateSeo(`${j.title} em Teodoro Sampaio | IntegraTrampo`,`${j.title} · ${j.company||'Contratante aprovado'} · ${j.rate?money(j.rate)+'/dia':'valor a combinar'}. Veja esta oportunidade na IntegraTrampo.`);modal(`<div class="notice">✅ <b>Vaga real publicada.</b> Candidaturas ficam protegidas entre profissional, contratante e operação.</div><h2>${esc(j.title)}</h2><p class="muted">${esc(j.company||'Contratante aprovado')} · ${esc(j.cat)} · ${esc(j.city||'Teodoro Sampaio - SP')}</p>${j.description?`<p>${esc(j.description)}</p>`:''}<div class="premium-detail-grid"><div class="premium-detail-box"><strong>📅 ${esc(dateLabel(j.service_date||j.date))}</strong><span>data do serviço</span></div><div class="premium-detail-box"><strong>${j.rate?money(j.rate):'A combinar'}</strong><span>diária</span></div><div class="premium-detail-box"><strong>${Number(j.v||1)}</strong><span>vaga(s)</span></div></div><div class="modal-actions"><button class="btn btn--green" onclick="applyRealJob?.('${esc(id)}')">Tenho interesse</button><button class="btn btn--outline" onclick="toggleFav('${esc(id)}')">♡ Favoritar</button><button class="btn btn--outline" onclick="shareIntegraTrampo?.('job','${esc(id)}')">Compartilhar</button><button class="btn btn--outline" onclick="closeModal()">Fechar</button></div>`)};

  window.openCompany=function(id){if(!isReal(id))return oldOpenCompany?.(id);const c=(typeof publicCompanies!=='undefined'?publicCompanies:[]).find(x=>String(x.id)===String(id));if(!c)return oldOpenCompany?.(id);updateSeo(`${c.name} | Contratante na IntegraTrampo`,`${c.name} · ${c.kind||'Contratante'} em ${c.city||'Teodoro Sampaio'}. Cadastro aprovado na IntegraTrampo.`);modal(`<div class="notice">✅ <b>Contratante aprovado pela IntegraTrampo.</b></div><div class="premium-detail-hero"><img src="${esc(c.img)}" alt="Identificação de ${esc(c.name)}"><div><h2>${esc(c.name)}</h2><div class="muted">${esc(c.kind||'Contratante')} · ${esc(c.city||'Teodoro Sampaio - SP')}</div><div style="margin-top:7px"><span class="premium-pill">✅ Cadastro aprovado</span></div></div></div>${c.description?`<p>${esc(c.description)}</p>`:''}<div class="premium-detail-grid"><div class="premium-detail-box"><strong>⭐ ${Number(c.rating||0)}</strong><span>reputação</span></div><div class="premium-detail-box"><strong>${Number(c.reviews||c.jobs||0)}</strong><span>avaliações</span></div><div class="premium-detail-box"><strong>Local</strong><span>atuação</span></div></div><div class="modal-actions"><button class="btn btn--outline" onclick="closeModal()">Fechar</button></div>`)};

  async function personalizeHome(){
    const home=$id('screen-home'),hero=home?.querySelector('.hero');if(!home||!hero)return;let box=$id('premiumPersonal');if(!currentUser){box?.remove();return}if(!box){box=document.createElement('div');box.id='premiumPersonal';box.className='premium-personal';hero.insertAdjacentElement('afterend',box)}
    const content=preferenceMode==='worker'?{ey:'👤 Para quem quer trabalhar',title:'Seu próximo trampo pode estar aqui.',p:'Veja vagas novas, ajuste sua disponibilidade e acompanhe candidaturas sem sair do painel.',a:'<button class="btn btn--green" data-go="vagas">Ver vagas</button><button class="btn btn--outline" data-go="painel">Meu painel</button>'}:preferenceMode==='hirer'?{ey:'🏢 Para quem precisa contratar',title:'Encontre gente disponível mais rápido.',p:'Filtre profissionais por disponibilidade, diária e transporte; salve os melhores e acompanhe seus pedidos.',a:'<button class="btn btn--orange" data-go="profissionais">Buscar profissionais</button><button class="btn btn--outline" data-go="painel">Minhas vagas</button>'}:{ey:'🤝 Experiência completa',title:'Trabalhe, contrate e acompanhe tudo em um só lugar.',p:'Sua conta pode usar os dois lados da IntegraTrampo, com favoritos e histórico sincronizados.',a:'<button class="btn btn--green" data-go="vagas">Ver vagas</button><button class="btn btn--orange" data-go="profissionais">Ver profissionais</button>'};box.innerHTML=`<div><span class="eyebrow">${content.ey}</span><h2>${content.title}</h2><p>${content.p}</p></div><div class="premium-personal__actions">${content.a}</div>`;box.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
  }

  async function loadPreference(){if(!sb||!currentUser){preferenceMode='both';return}try{const {data}=await sb.from('it_user_preferences').select('mode').eq('user_id',currentUser.id).maybeSingle();preferenceMode=data?.mode||'both'}catch{preferenceMode='both'}}
  async function openDeepLinkPremium(){const p=new URLSearchParams(location.search),job=p.get('job'),pro=p.get('pro'),company=p.get('company');if(!job&&!pro&&!company)return;for(let i=0;i<30;i++){if(job&&(typeof publicJobs!=='undefined'?publicJobs:[]).some(x=>String(x.id)===job)){openJob(job);return}if(pro&&(typeof publicPros!=='undefined'?publicPros:[]).some(x=>String(x.id)===pro)){openPro(pro);return}if(company&&(typeof publicCompanies!=='undefined'?publicCompanies:[]).some(x=>String(x.id)===company)){openCompany(company);return}await wait(150)}}

  async function init(){
    if(initialized)return;initialized=true;injectStyles();for(let i=0;i<100&&!window.IntegraTrampoSupabase;i++)await wait(80);sb=window.IntegraTrampoSupabase||null;if(sb){try{currentUser=(await sb.auth.getUser()).data?.user||null}catch{}await loadPreference();await enrichPublicData()}installExtraFilters();installResetHooks();renderPros();renderJobs();renderCompanies();if(typeof oldRenderHome==='function')oldRenderHome();await personalizeHome();await openDeepLinkPremium();
    if(sb)sb.auth.onAuthStateChange((event,session)=>setTimeout(async()=>{currentUser=session?.user||null;await loadPreference();await personalizeHome()},0));
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();